// Using recommended parameters from whitepaper https://eprint.iacr.org/2019/458.pdf (table 2, table 8)
// Generated by https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/calc_round_numbers.py
// And rounded up to nearest integer that divides by t

use halo2::halo2curves::bn256::Fr;

pub fn n_rounds_p() -> [usize; 3] {
    [56, 57, 56]
}

pub fn t(inputs: Vec<Fr>) -> usize {
    inputs.len() + 1
}

pub fn n_rounds_t() -> usize {
    8
}
